# Generated by Django 3.1.4 on 2021-06-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_converted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organiser',
            new_name='is_organisor',
        ),
    ]
